### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by jweisman** [ExLibrisGroup/cloudapp-sdk#40]
Reported in [Cloud App Forum](https://developers.exlibrisgroup.com/forums/topic/unable-to-resolve-dependency-tree/)

Looks like it’s related to a breaking change npm v7 around conflicting peer dependencies. https://github.blog/2021-02-02-npm-7-is-now-generally-available/

Running `npm install –legacy-peer-dep` before `eca start` seems to have worked. The root cause seems to be @exlibris/exl-cloudapp-angular-lib having peer dependencies on exactly specific versions of @angular packages.

```
After creating an empty dir and then running «eca init» inside that dir, «eca start» fails with the error «ERESOLVE unable to resolve dependency tree»

eca: ‘v0.5.0’, node: ‘14.16.0’, npm: ‘7.6.0’, macos: ‘10.15.7’

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-exl-cloudapp@1.0.0
npm ERR! Found: @angular/core@9.1.13
npm ERR! node_modules/@angular/core
npm ERR! @angular/core@”^9.1.0″ from the root project
npm ERR! peer @angular/core@”^9.0.0 || ^10.0.0-0″ from @angular/material@9.2.4
npm ERR! node_modules/@angular/material
npm ERR! @angular/material@”^9.2.0″ from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@”10.2.4″ from @angular/animations@10.2.4
npm ERR! node_modules/@angular/animations
npm ERR! peer @angular/animations@”^9.0.0 || ^10.0.0-0″ from @angular/material@9.2.4
npm ERR! node_modules/@angular/material
npm ERR! @angular/material@”^9.2.0″ from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with –force, or –legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/jim/.npm/eresolve-report.txt for a full report.
```

**Comment by d22** [comment]
I have similar issues with peer dependencies and CLI 1.0.5. I can't get the CloudApp environment to run when following the steps from the instruction:
```
 $> nvm use 14
Now using node v14.17.1 (npm v7.19.0)
 $> eca version
v1.0.2
 $> eca init

✔ App title:  … cloud3
✔ App subtitle:  … cloud3
✔ App author:  … Jonas Furrer
✔ Environment URL:  … https://slsp-hsg.alma.exlibrisgroup.com/institution/41SLSP_HSG
✔ Run dev server on port:  … 8080

Using config:
{
  env: 'https://slsp-hsg.alma.exlibrisgroup.com/institution/41SLSP_HSG',
  port: 8080
}

The following files and folders were created:
.gitignore
.ng
.vscode
cloudapp
config.json
manifest.json
node_modules
package.json

Done.

 $> npm install --legacy-peer-deps
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/animations/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/animations@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/animations [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/animations/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/animations/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/cdk/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/cdk@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/cdk [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/cdk/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/cdk/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/cli/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/cli@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/cli [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/cli/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/cli/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/common/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/common@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/common [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/common/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/common/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/compiler/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/compiler@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/compiler [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/compiler/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/compiler/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/forms/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/forms@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/forms [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/forms/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/forms/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/material/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/material@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/material [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/material/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/material/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/platform-browser/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/platform-browser@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/platform-browser [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/platform-browser/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/platform-browser/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/core/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/core@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/core [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/core/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/core/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/platform-browser-dynamic/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/platform-browser-dynamic@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/platform-browser-dynamic [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/platform-browser-dynamic/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/platform-browser-dynamic/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/router/package.json'
npm WARN old lockfile  Could not fetch metadata for @angular/router@file:/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/router [Error: ENOENT: no such file or directory, open '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/router/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/router/package.json'
npm WARN old lockfile }
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated tslib@1.12.0: TSLib 1.12.0 accidentally contained a breaking change and is not compatible with the output produced by TypeScript versions 3.8 or earlier - use tslib 1.13.0 for TS <=3.8, or TSLib 2.0.0 for TS >=3.9
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

added 1464 packages, removed 17 packages, changed 5 packages, and audited 1470 packages in 47s

81 packages are looking for funding
  run `npm fund` for details

23 vulnerabilities (5 low, 6 moderate, 12 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
 $> eca start

up to date, audited 1470 packages in 3s

81 packages are looking for funding
  run `npm fund` for details

24 vulnerabilities (5 low, 7 moderate, 12 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Using config:
{
  env: 'https://slsp-hsg.alma.exlibrisgroup.com/institution/41SLSP_HSG',
  port: 8080
}

⠴ Starting server...internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/Users/jonas/Projects/unisg/cloud3/node_modules/@angular/cli/bin/ng'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
⠦ Starting server...%
 $>`
```

**I get the environment running with the following steps:**

```
 $> nvm use 14
Now using node v14.17.1 (npm v7.19.0)
 $> eca version
v1.0.2
 $> eca init

✔ App title:  … cloud3
✔ App subtitle:  … cloud3
✔ App author:  … Jonas Furrer
✔ Environment URL:  … https://slsp-hsg.alma.exlibrisgroup.com/institution/41SLSP_HSG
✔ Run dev server on port:  … 8080

Using config:
{
  env: 'https://slsp-hsg.alma.exlibrisgroup.com/institution/41SLSP_HSG',
  port: 8080
}

The following files and folders were created:
.gitignore
.ng
.vscode
cloudapp
config.json
manifest.json
node_modules
package.json

Done.

 $> rm -r node_modules
 $> npm i --force
npm WARN using --force Recommended protections disabled.
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated tslib@1.12.0: TSLib 1.12.0 accidentally contained a breaking change and is not compatible with the output produced by TypeScript versions 3.8 or earlier - use tslib 1.13.0 for TS <=3.8, or TSLib 2.0.0 for TS >=3.9
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated querystring@0.2.0: The
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

added 1469 packages, and audited 1470 packages in 36s

81 packages are looking for funding
  run `npm fund` for details

25 vulnerabilities (5 low, 7 moderate, 13 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
 $> ls node_modules/@angular
 $> eca start

up to date, audited 1470 packages in 3s

81 packages are looking for funding
  run `npm fund` for details

25 vulnerabilities (5 low, 7 moderate, 13 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Using config:
{
  env: 'https://slsp-hsg.alma.exlibrisgroup.com/institution/41SLSP_HSG',
  port: 8080
}


Server is listening on port 8080.
Opening browser on http://localhost:8080/institution/41SLSP_HSG.

: Compiled successfully.
```
But I'm still not able to work, since the login does not work. After logging in, I always get redirected to back to the login page. The behaviour is the same on Windows and OSX, and also the same with Node 16.x.x. 
So currently we are completely blocked from working on CloudApps, any hint or help on how to fix this is appreciated.

BR
Jonas

**Comment by jweisman** [comment]
Hi Jonas. Id' like to help with this. Can you reach out to me - josh.weisman at exlibrisgroup?

**Comment by jweisman** [comment]
Hi all- we've released a version of the SDK which updates to Angular 11. We'd be happy if you would test a new app using the [latest version](https://github.com/ExLibrisGroup/cloudapp-sdk/releases/tag/v1.4.0). It should work with Node 14 or 16 / npm 6 /7. 

Information about updating existing apps is available on this [page in the docs](https://developers.exlibrisgroup.com/cloudapps/docs/updating/).

**Comment by jweisman** [comment]
Hi @d22- I've opened another issue for your log in issue- #48

**Comment by jweisman** [comment]
Closing this as it seems the updated SDK version solves the dependency tree problem.
